
/** populate the tables during the startup */

INSERT INTO SLOT (TYPE, BILLING_POLICY, IS_AVAILABLE) VALUES ('EV-50KW', 1, TRUE);
INSERT INTO SLOT (TYPE, BILLING_POLICY, IS_AVAILABLE) VALUES ('EV-50KW', 1, TRUE);
INSERT INTO SLOT (TYPE, BILLING_POLICY, IS_AVAILABLE) VALUES ('EV-20KW', 1, TRUE);
INSERT INTO SLOT (TYPE, BILLING_POLICY, IS_AVAILABLE) VALUES ('EV-20KW', 1, TRUE);
INSERT INTO SLOT (TYPE, BILLING_POLICY, IS_AVAILABLE) VALUES ('sedan', 2, TRUE);
INSERT INTO SLOT (TYPE, BILLING_POLICY, IS_AVAILABLE) VALUES ('sedan', 2, TRUE);


/*
UPDATE SLOT SET IS_AVAILABLE = FALSE WHERE ID=4;

INSERT INTO RESERVATION (SLOT_ID, CAR_ID, BILLING_POLICY) VALUES (1, 'EV-XXX-YY', 1);
*/